"use client";

import Link from "next/link";
import {
  ArrowRight, BarChart3, Building2, Bus, Check, ChevronRight, Factory,
  GraduationCap, Hammer, HardHat, HeartPulse, Hotel, Landmark, Leaf,
  Menu, ShoppingBag, Stethoscope, Tractor, Truck,
  Users, Utensils, Wrench, X,
} from "lucide-react";
import { FormEvent, useState } from "react";

const sectors = [
  { name: "Industrie & Production", summary: "GPAO, Traçabilité, TRS", icon: Factory, color: "#8754ef", soft: "#eee7ff", description: "Orchestrez l’ensemble de votre chaîne de production. De la gestion des nomenclatures à la supervision en temps réel des lignes, optimisez vos flux et garantissez la traçabilité complète de vos produits finis.", kpi: "84.2%", kpiLabel: "Taux Rendement Synthétique", modules: ["Gestion Nomenclatures (BOM)", "Planification Sous-traitance", "Contrôle Qualité", "Maintenance (GMAO)"] },
  { name: "Retail & E-commerce", summary: "Omnicanal, Stocks, POS", icon: ShoppingBag, color: "#0dbf8a", soft: "#e7f8f3", description: "Unifiez magasins, e-commerce et stocks dans une expérience omnicanale fluide. Pilotez vos ventes, vos marges et vos approvisionnements depuis une seule plateforme.", kpi: "+18%", kpiLabel: "Croissance du panier moyen", modules: ["Caisse & POS", "E-commerce", "Stocks Omnicanaux", "Fidélité Client"] },
  { name: "Santé & Médico-social", summary: "DPI, Facturation, Planning", icon: Stethoscope, color: "#10aee8", soft: "#e5f6fc", description: "Sécurisez les parcours patients, coordonnez les équipes et automatisez la facturation. Une gestion conforme, pensée pour les établissements de santé et médico-sociaux.", kpi: "99.8%", kpiLabel: "Disponibilité des dossiers", modules: ["Dossier Patient", "Planning Soignant", "Facturation", "Stocks Pharmacie"] },
  { name: "BTP & Construction", summary: "Chantiers, Matériel, RH", icon: Wrench, color: "#f2a30a", soft: "#fff3df", description: "Maîtrisez la rentabilité de chaque chantier, l’affectation des équipes et la disponibilité du matériel. Anticipez les écarts et suivez l’avancement en direct.", kpi: "-22%", kpiLabel: "Écarts budgétaires", modules: ["Suivi de Chantier", "Parc Matériel", "Achats Projet", "Main-d’œuvre"] },
  { name: "Agroalimentaire", summary: "Lots, DLC, Qualité", icon: Tractor, color: "#73c621", soft: "#eef8e4", description: "Assurez la traçabilité des lots, la gestion des dates limites et la conformité qualité de la matière première au produit fini.", kpi: "100%", kpiLabel: "Lots tracés", modules: ["Lots & Traçabilité", "DLC/DLUO", "Recettes", "Qualité"] },
  { name: "Transport & Logistique", summary: "Flotte, WMS, Itinéraires", icon: Truck, color: "#6868ed", soft: "#ededff", description: "Optimisez les tournées, le taux de remplissage et la gestion de flotte. Gardez une visibilité continue sur chaque livraison et chaque entrepôt.", kpi: "-16%", kpiLabel: "Coût par livraison", modules: ["Gestion de Flotte", "WMS", "Planification", "Preuve de Livraison"] },
  { name: "Services & Conseil", summary: "Projets, Temps, Facturation", icon: Users, color: "#ef58ad", soft: "#fde8f4", description: "Pilotez vos missions, les temps passés et la rentabilité des consultants. Automatisez la facturation selon vos jalons et contrats.", kpi: "+12%", kpiLabel: "Taux d’occupation", modules: ["Gestion de Projets", "Feuilles de Temps", "Facturation", "Plan de Charge"] },
  { name: "Hôtellerie", summary: "Réservations, PMS, Achats", icon: Hotel, color: "#d65d5d", soft: "#fbeaea", description: "Centralisez réservations, housekeeping, achats et pilotage financier pour offrir une expérience client irréprochable.", kpi: "+9%", kpiLabel: "Taux d’occupation", modules: ["PMS", "Housekeeping", "Achats", "Revenue Management"] },
  { name: "Restauration", summary: "Stocks, Recettes, Marges", icon: Utensils, color: "#e17a32", soft: "#fff0e5", description: "Standardisez vos recettes, réduisez les pertes et suivez vos marges par établissement, service et produit.", kpi: "-14%", kpiLabel: "Pertes matières", modules: ["Fiches Techniques", "Stocks", "Commandes", "Marges"] },
  { name: "Immobilier", summary: "Biens, Baux, Charges", icon: Building2, color: "#417ab7", soft: "#e8f1fa", description: "Gérez votre patrimoine, vos baux et vos interventions avec une vision financière consolidée de chaque actif.", kpi: "96%", kpiLabel: "Taux de recouvrement", modules: ["Patrimoine", "Baux", "Charges", "Maintenance"] },
  { name: "Finance", summary: "Risques, Conformité, Reporting", icon: Landmark, color: "#365fa5", soft: "#e8eef8", description: "Accélérez vos clôtures, fiabilisez vos contrôles et disposez d’un reporting réglementaire toujours à jour.", kpi: "-40%", kpiLabel: "Temps de clôture", modules: ["Comptabilité", "Risques", "Conformité", "Consolidation"] },
  { name: "Éducation", summary: "Scolarité, Planning, Finance", icon: GraduationCap, color: "#895ab8", soft: "#f1eafb", description: "Simplifiez la gestion des inscriptions, des emplois du temps, de la facturation et des ressources pédagogiques.", kpi: "92%", kpiLabel: "Taux de satisfaction", modules: ["Scolarité", "Planning", "Facturation", "Portail Étudiant"] },
  { name: "Agriculture", summary: "Parcelles, Cultures, Coûts", icon: Leaf, color: "#4e9f51", soft: "#e9f6e9", description: "Suivez parcelles, campagnes, intrants et rendements pour prendre des décisions fondées sur vos données terrain.", kpi: "+11%", kpiLabel: "Rendement moyen", modules: ["Parcelles", "Campagnes", "Intrants", "Matériel"] },
  { name: "Secteur Public", summary: "Budget, Marchés, Services", icon: Bus, color: "#4f657a", soft: "#eaf0f5", description: "Modernisez les processus publics, sécurisez l’exécution budgétaire et améliorez le suivi des services aux citoyens.", kpi: "100%", kpiLabel: "Traçabilité budgétaire", modules: ["Budget", "Marchés Publics", "Patrimoine", "Services Citoyens"] },
];

export default function SectorsPage() {
  const [active, setActive] = useState(0);
  const [menuOpen, setMenuOpen] = useState(false);
  const [subscribed, setSubscribed] = useState(false);
  const sector = sectors[active];
  const Icon = sector.icon;
  function subscribe(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubscribed(true); }

  return <main className="overflow-x-clip bg-white">
    <header className="sticky top-0 z-50 h-[68px] border-b border-brand-line bg-white/95 backdrop-blur-xl md:h-[78px]">
      <div className="mx-auto flex h-full max-w-[1220px] items-center justify-between px-5 md:px-7">
        <Brand />
        <nav className={`${menuOpen ? "flex" : "hidden"} absolute inset-x-0 top-[68px] flex-col border-b border-brand-line bg-white p-5 shadow-lg md:static md:ml-auto md:mr-8 md:flex md:flex-row md:items-center md:gap-8 md:border-0 md:p-0 md:shadow-none`}>
          <Link className="px-3 py-3 text-sm font-semibold text-[#4d5360] md:px-0" href="/">Accueil</Link><Link className="px-3 py-3 text-sm font-semibold text-[#4d5360] md:px-0" href="/solutions">Solutions</Link><Link className="px-3 py-3 text-sm font-bold text-brand-blue md:px-0" href="/secteurs">Secteurs</Link><Link className="px-3 py-3 text-sm font-semibold text-[#4d5360] md:px-0" href="/#methode">Méthodologie</Link><Link className="px-3 py-3 text-sm font-semibold text-[#4d5360] md:px-0" href="/contact">Contact</Link>
        </nav>
        <Link className="hidden rounded-lg bg-brand-blue px-5 py-3 text-sm font-bold text-white hover:bg-brand-blue-dark md:block" href="/contact">Réserver une démo</Link><button className="p-2 md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Ouvrir le menu">{menuOpen ? <X /> : <Menu />}</button>
      </div>
    </header>

    <section className="bg-gradient-to-br from-[#fdfbfc] to-[#f3f1f6]">
      <div className="mx-auto max-w-[1220px] px-5 pb-20 pt-16 md:px-7 md:pb-24 md:pt-20">
        <div className="mx-auto max-w-[740px] text-center"><h1 className="font-display text-[44px] font-bold leading-tight text-black md:text-[60px]">Un ERP conçu<br/><em className="font-normal">autour de votre métier</em></h1><p className="mx-auto mt-6 max-w-[670px] text-[18px] leading-[1.55] text-[#5f626a]">Découvrez comment nos solutions verticalisées répondent aux défis spécifiques de votre industrie, avec des modules pré-configurés et des indicateurs de performance adaptés.</p><span className="mx-auto mt-8 block h-1 w-24 rounded bg-[#dfdde1]" /></div>
        <div className="mt-10 grid items-start gap-8 lg:grid-cols-[.75fr_1.25fr]">
          <div><h2 className="mb-6 font-display text-[25px] font-bold text-black">Secteurs (14)</h2><div className="max-h-[730px] space-y-2 overflow-y-auto pr-2">{sectors.map(({ name, summary, icon: ItemIcon, color, soft }, index) => <button className={`flex w-full items-center rounded-xl border p-4 text-left transition ${active === index ? "border-[#c9c6cd] bg-[#e9e6e9]" : "border-transparent hover:bg-white"}`} key={name} onClick={() => setActive(index)}><span className="grid size-12 shrink-0 place-items-center rounded-lg" style={{ backgroundColor: active === index ? color : soft, color: active === index ? "white" : color }}><ItemIcon size={23}/></span><span className="ml-4 min-w-0 flex-1"><b className="block truncate font-display text-[18px] text-[#25242a]">{name}</b><small className="mt-1 block truncate text-sm text-[#65656c]">{summary}</small></span><ChevronRight className="ml-3 shrink-0 text-[#555960]" size={22}/></button>)}</div><p className="mt-6 text-center text-sm text-[#63666d]">Faites défiler pour voir les 14 secteurs</p></div>
          <article className="overflow-hidden rounded-[22px] border border-[#cbc9d0] bg-white shadow-sm">
            <div className="relative p-7 md:p-9" style={{ background: `linear-gradient(135deg, #fff 20%, ${sector.soft})` }}><div className="flex items-center gap-3 text-xs font-extrabold uppercase tracking-[.12em] text-[#52535a]"><Icon size={25} style={{ color: sector.color }}/><span>Fiche sectorielle</span></div><h2 className="mt-5 max-w-[520px] font-display text-[43px] font-bold leading-[1.02] text-black md:text-[55px]">{sector.name}</h2><p className="mt-7 max-w-[610px] text-[16px] leading-[1.55] text-[#666870]">{sector.description}</p><Link className="mt-7 inline-flex items-center gap-2 rounded-xl px-6 py-3 font-bold text-white shadow-lg md:absolute md:right-8 md:top-8 md:mt-0" style={{ backgroundColor: sector.color }} href="/contact">Voir la démo <ArrowRight size={18}/></Link></div>
            <div className="border-t border-[#e4e1e6] p-6 md:p-8"><div className="flex items-center justify-between"><h3 className="font-display text-[25px] font-bold text-black">Aperçu Interface</h3><span className="flex gap-2">{[0,1,2].map(n => <i className="size-3 rounded-full bg-[#dddce0]" key={n}/>)}</span></div><InterfacePreview sector={sector} /></div>
            <div className="border-t border-[#e2dfe4] bg-[#f5f3f5] px-5 py-4"><b className="text-xs tracking-wide text-[#5c5d64]">Modules Clés</b><div className="mt-3 flex flex-wrap gap-2">{sector.modules.map(module => <span className="rounded-full border border-[#e1dee3] bg-white px-3 py-1.5 text-sm text-[#4e5057]" key={module}>{module}</span>)}</div></div>
          </article>
        </div>
      </div>
    </section>

    <footer className="border-t border-brand-line bg-white px-5 pb-7 pt-14" id="contact"><div className="mx-auto grid max-w-[1164px] gap-9 sm:grid-cols-2 lg:grid-cols-[1.2fr_.9fr_.9fr_1.1fr_1.2fr]"><div><Brand/><p className="mt-4 max-w-[190px] text-[13px] leading-5 text-brand-muted">L’excellence opérationnelle au service de votre croissance.</p></div><FooterColumn title="Solutions" links={["Gestion Financière", "Chaîne Logistique", "Ressources Humaines", "Intelligence Client"]}/><FooterColumn title="Secteurs" links={["Industrie", "Retail & Commerce", "Services & Santé", "Secteur Public"]}/><div><b className="text-[11px] uppercase tracking-wider">Contact</b></div><div><b className="text-[11px] uppercase tracking-wider">Newsletter</b>{subscribed ? <p className="mt-4 text-sm text-[#168356]">Merci, à bientôt !</p> : <form className="mt-4 flex flex-col gap-2" onSubmit={subscribe}><input className="rounded-md border border-[#bdc4cf] px-3 py-2.5 text-sm" type="email" required placeholder="votre@email.com"/><button className="rounded-md bg-black py-2.5 text-sm font-bold text-white">S’abonner</button></form>}</div></div><div className="mx-auto mt-14 max-w-[1164px] border-t border-brand-line pt-6 text-xs text-[#737b88]">© 2026 GSM ERP. Tous droits réservés.</div></footer>
  </main>;
}

function InterfacePreview({ sector }: { sector: typeof sectors[number] }) { return <div className="mt-6 overflow-hidden rounded-xl border border-[#dfdde2] bg-[#fbfafc] p-5 shadow-inner"><div className="flex items-center justify-between rounded-lg border border-[#ebe8ed] bg-white p-3"><span className="h-3 w-32 rounded bg-[#eeebef]"/><span className="flex gap-2"><i className="size-8 rounded bg-[#efedf0]"/><i className="size-8 rounded-full bg-[#efedf0]"/></span></div><div className="mt-6 grid gap-5 md:grid-cols-[.6fr_1.4fr]"><div><small className="block max-w-[120px] text-[11px] font-bold leading-3 text-[#585a62]">{sector.kpiLabel}</small><b className="mt-2 block font-display text-[34px] text-[#24252a]">{sector.kpi}</b><div className="mt-4 flex h-16 items-end gap-2">{[24,32,47,42,61].map((h,i) => <span className="flex-1 rounded-t" key={i} style={{ height: h, backgroundColor: sector.color, opacity: .35 + i * .12 }}/>)}</div></div><div><div className="flex items-center justify-between"><b className="text-sm">Pilotage {sector.name}</b><span className="rounded bg-[#eeecef] px-2 py-1 text-[10px]">Semaine</span></div><svg className="mt-5 h-[130px] w-full" viewBox="0 0 420 130" aria-label={`Tendance ${sector.name}`}><defs><linearGradient id="sectorArea" x1="0" y1="0" x2="0" y2="1"><stop stopColor={sector.color} stopOpacity=".5"/><stop offset="1" stopColor={sector.color} stopOpacity=".04"/></linearGradient></defs><path d="M0 108 C45 92,70 105,110 75 S180 93,220 53 S285 80,330 42 S380 51,420 17 L420 130 L0 130Z" fill="url(#sectorArea)"/><path d="M0 108 C45 92,70 105,110 75 S180 93,220 53 S285 80,330 42 S380 51,420 17" fill="none" stroke={sector.color} strokeWidth="3"/></svg></div></div></div>; }
function Brand() { return <Link className="inline-flex items-center whitespace-nowrap font-display text-xl font-bold text-black" href="/">GSM ERP</Link>; }
function FooterColumn({ title, links }: { title: string; links: string[] }) { return <div><b className="text-[11px] uppercase tracking-wider">{title}</b><div className="mt-4 flex flex-col gap-2.5">{links.map(link => <a className="text-[13px] text-brand-muted hover:text-brand-blue" href="#" key={link}>{link}</a>)}</div></div>; }
